AWSTemplateFormatVersion: "2010-09-09"
Description: This template creates an IAM role with administrator access and a trust relationship with another AWS account.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Cross Account Role Definitions"
        Parameters:
          - PrincipalAccountID
Parameters:
  PrincipalAccountID:
    Type: Number
    Description: Principal Account ID
Resources:
  ControlTowerRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: AWSControlTowerExecution
      Policies:
        - PolicyName: FullAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AWSControlTowerExecution
                Action: '*'
                Resource: '*'
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${PrincipalAccountID}:root
Outputs:
  CrossAccountRoleArn:
    Description: Cross Account Role for ControlTower
    Value:
      Fn::GetAtt:
        - ControlTowerRole
        - Arn